services:
  pg:
    image: bitnami/postgresql
    ports:
      - '5432:5432'
    environment:
      - "POSTGRES_USER=calendar"
      - "POSTGRES_PASSWORD=calendar"
      - "POSTGRES_DB=calendar"
    restart: always
